### ISSUE TITLE
focus project selection on project names instead of path/to/inlang.project to reduce cognitive load

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#37]
### Context

It's overwhelming to look at the project selection. 

* long paths that are hard to read
* paths have duplicate information to project name e.g. `website/website.inlang` is twice "ah this is the website project"

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/56d45192-5b19-49bc-859d-d84c4df3d2dd/463931da-0edd-4c71-9e2c-ea862794b6e8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC81NmQ0NTE5Mi01YjE5LTQ5YmMtODU5ZC1kODRjNGRmM2QyZGQvNDYzOTMxZGEtMGVkZC00YzcxLTllMmMtZWE4NjI3OTRiNmU4IiwiaWF0IjoxNzE4MjUzNzY1LCJleHAiOjMzMjg4ODEzNzY1fQ.sgL2e-UTeUcPESD0Yl8pH3rTHZcOHhFm9i7z9VVD4WU " alt="CleanShot 2024-06-13 at 06.27.31@2x.png" width="800" height="786" />

### Proposal

Focus the project selection around project names by giving the path less importance by: 

1. Only display the project name in the dropdown selector
2. Put the main focus in the dropdown selector on the project names, not paths
3. Remove `{name}.inlang` files from the path because every path ends with `.inlang` and `{name}` is shown at the beginning. There is no additional value in showing it.  

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/70f7fd54-4b30-4df9-895e-42890ba8fce3/d37295c7-ff14-48b3-b23b-dcac9285dcb2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC83MGY3ZmQ1NC00YjMwLTRkZjktODk1ZS00Mjg5MGJhOGZjZTMvZDM3Mjk1YzctZmYxNC00OGIzLWIyM2ItZGNhYzkyODVkY2IyIiwiaWF0IjoxNzE4MjUzNzY1LCJleHAiOjMzMjg4ODEzNzY1fQ.QQ13jnl71DIhKQHtnUEf_t6Cw0GucB3CtmrAju44oU8 " alt="CleanShot 2024-06-13 at 06.32.25@2x.png" width="1382" height="902" />

### Additional information 

* this nudges users to name their projects \[to avoid a project, project, project list\]. imo this is good
* the proposal aligns with how we use web apps, see the figma screenshot

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/af545a1e-56fd-4f70-bfd3-d19c2c84b362/498cf446-c811-4b86-b94e-222280403d72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hZjU0NWExZS01NmZkLTRmNzAtYmZkMy1kMTljMmM4NGIzNjIvNDk4Y2Y0NDYtYzgxMS00Yjg2LWI5NGUtMjIyMjgwNDAzZDcyIiwiaWF0IjoxNzE4MjUzNzY1LCJleHAiOjMzMjg4ODEzNzY1fQ.KHzwBlyPQ0I77sUBkhbBM3ezRpzbxGIrDDPL6A3jgVE " alt="CleanShot 2024-06-13 at 06.36.34@2x.png" width="1530" height="980" />

### Tasks

- [ ] (1) only show project name in dropdown selector
- [ ] (2) main focus on project name instead of path in dropdown menu
- [ ] (3) directory path doesn't show {name}.inlang
- [ ] directory path shows dots (`../*`) to indicate that the path is shortened (see [FINK-44](https://linear.app/opral/issue/FINK-44/why-did-it-add-source-code-in-project-dropdown-or-fink))
